export const GET_ORDER_START = 'GET_ORDER_START'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR'

export const GET_ORDER_BY_USER_START = 'ADD_ORDER_START'
export const GET_ORDER_BY_USER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const GET_ORDER_BY_USER_ERROR = 'ADD_ORDER_ERROR'

export const PLACE_ORDER_START = 'DELETE_ORDER_START'
export const PLACE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const PLACE_ORDER_ERROR = 'DELETE_ORDER_ERROR'


